chore: update project

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,8 @@
-npx --no-install lint-staged
-npx -p prettier@latest
+echo "🛠️  Running lint-staged..."
+
+npx lint-staged
+if [ $? -ne 0 ]; then
+  echo "🚨  lint-staged failed"
+  exit 1
+fi
+echo "🛠️✅  lint-staged passed"
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,7 +1,17 @@
-npx --no-install lint-staged
+
+echo "🧪  Starting a test check" 
+
 npm run test:deploy --findRelatedTests --bail
-npm run build  # Substitua isso pelo comando de construção real que você está usando
 if [ $? -ne 0 ]; then
-  echo "A construção falhou. Não é possível fazer push."
+  echo "🧪⚠️  The tests failed. Push is not possible."
   exit 1
 fi
+echo "🧪  Tests passed. Pushing to the repository."
+
+echo "📦  Starting a build check"
+npm run build
+if [ $? -ne 0 ]; then
+  echo "📦⚠️  A construção falhou. Não é possível fazer push."
+  exit 1
+fi
+echo "📦  Build succeeded. Pushing to the repository."
